provider:
  name: faas
  gateway: http://localhost:9080  # can be a remote server

functions:
  reacthello:
    lang: dockerfile
    handler: ./ReactHello
    image: react-hello

functions:
  reactprops:
    lang: dockerfile
    handler: ./ReactProps
    image: react-props

functions:
  reactBtn:
    lang: dockerfile
    handler: ./ReactButton
    image: react-btn